name: maps
version: 0.0.1
author: 7c00 <i@7c00.cc>

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: qiuxiang.maps
        pluginClass: MapsPlugin
